[metadata]
name = pv_naming
version = file: pv_naming/VERSION
author = riw56156
author_email = riw56156@fed.cclrc.ac.uk
description = Module

[options]
packages = find:
zip_safe = False
install_requires =
    requests
    natsort

[options.entry_points]
console_scripts =
    builder-ioc-naming-report = pv_naming.command_line.builder_report:command_line_report_builder_iocs
    device-name-check = pv_naming.command_line.checker:command_line_check

[flake8]
ignore = E203, E266, E501, W503, F403, F401
max-line-length = 79
max-complexity = 18
select = B,C,E,F,W,T4,B9